name: TownyCivilizations
version: 1.0
main: io.github.eggsdevs.townycivilizations.TownyCivilizations
api-version: 1.21
depend: [Towny]
commands:
  townycivilizations:
    description: Shows a brief overview of Towny Civilizations.
    usage: /townycivilizations
    permission: townycivilizations.use
  mayoraldesks:
    description: Lists all active Mayoral Desks.
    usage: /mayoraldesks [page]
    permission: townycivilizations.mayoraldesks
permissions:
  townycivilizations.use:
    description: Allows use of /townycivilizations
    default: true
  townycivilizations.mayoraldesks:
    description: Allows listing of Mayoral Desks
    default: op